apiVersion: v1
kind: Service
metadata:
  name: patch-admission-manager
  labels:
    app: cdp-patch-admission-customizer
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: cdp-patch-admission-customizer
